---
title: "Plasmodium Nested Species: Run Summary"
header-includes:
   - \usepackage[default]{sourcesanspro}
   - \usepackage[T1]{fontenc}
mainfont: SourceSansPro
classoption: landscape
params:
  sub_directory: sub_directory
  project: projet
  assay: assay
  plate_folder: plate_folder
---
```{r setup, include=FALSE}
library(here)
knitr::opts_chunk$set(echo = FALSE, fig.width=12, fig.height=7, warning = F,message = F)


data <- classifyNestedSpecies(sub_directory = params$sub_directory,
                          project = params$project,
                          assay = params$assay,
                          plate_folder = params$plate_folder)



```

### Plate name: `r paste0(unique(data[[6]][[1]]$plate_name))`
### Run on the: `r paste0(data[[6]][[4]])`
### Run by: `r paste0(data[[6]][[5]])`


\newpage

```{r plate map, warning=F}
data[[4]]
```

```{r melt temperatures 1,warning=F}
data[[1]]
```

```{r melt temperatures 2,warning=F}
data[[2]]
```

```{r amplification curve, warning=F}
data[[3]]
```

```{r plate map primers,warning=F}
data[[5]]
```

```{r write results, include = F, warning = F}
file_name <- paste0(params$project, "-", params$plate_folder, "_nested_species_results.xlsx")

to_save <- data[[6]][[1]] %>% 
  dplyr::select(sample_id, well_position,  plate_name, ct, tm1,primers = nested_species, derivative_max, classification = classification_global)	%>% 
  split(~primers)	


for (i in 1:length(to_save)) {
  
  colnames(to_save[[i]]) <- paste0(colnames(to_save[[i]]), "_", unique(to_save[[i]]$primers), "_nested")
  
  to_save[[i]] <- to_save[[i]] %>%  
    janitor::clean_names() %>% 
    dplyr::select(!starts_with("primers")) %>% 
    dplyr::rename(sample_id = starts_with("sample_id"))
}


to_save <- to_save%>%
    purrr::reduce(function(x, y) dplyr::full_join(x, y, by = c("sample_id"))) 

results <- openxlsx::createWorkbook()
openxlsx::addWorksheet(results, "nested_species", gridLines = T)
openxlsx::writeData(results, "nested_species", to_save)

format_spp_pos <- openxlsx::createStyle(bgFill = "#BC2728")
format_spp_neg <- openxlsx::createStyle(bgFill = "#BCD7FB")
style_rounded = openxlsx::createStyle(numFmt="0.00")

openxlsx::conditionalFormatting(results, "nested_species", 1:ncol(to_save), rule = "positive", style = format_spp_pos, type = "contains", rows = 1:nrow(to_save)+1)

openxlsx::conditionalFormatting(results, "nested_species", 1:ncol(to_save), rule = "negative", style = format_spp_neg, type = "contains", rows = 1:nrow(to_save)+1)

openxlsx::addStyle(results, "nested_species", style_rounded, rows = 1:nrow(to_save)+1, cols =4)
openxlsx::addStyle(results, "nested_species", style_rounded, rows = 1:nrow(to_save)+1, cols =5)
openxlsx::addStyle(results, "nested_species", style_rounded, rows = 1:nrow(to_save)+1, cols =6)
openxlsx::addStyle(results, "nested_species", style_rounded, rows = 1:nrow(to_save)+1, cols =10)
openxlsx::addStyle(results, "nested_species", style_rounded, rows = 1:nrow(to_save)+1, cols =11)
openxlsx::addStyle(results, "nested_species", style_rounded, rows = 1:nrow(to_save)+1, cols =12)



openxlsx::writeDataTable(results, "nested_species", to_save, startRow = 1, startCol = 1, tableStyle = "TableStyleLight9")


width_vec <- apply(to_save, 2, function(x) max(nchar(as.character(x)) + 2, na.rm = TRUE))
dth_vec_header <- nchar(colnames(to_save))  + 2

width_vec <- dplyr::bind_cols(text = width_vec, header = dth_vec_header) %>% 
  dplyr::mutate(col_no = paste0("col", 1:length((to_save)))) %>%
  tidyr::pivot_longer(-col_no) %>% 
  dplyr::mutate(value = dplyr::case_when(
    value==Inf ~0, 
     TRUE~value))  %>% 
  dplyr::group_by(col_no) %>%  
  dplyr::filter(value == max(value)) %>% 
  dplyr::ungroup() %>% 
  dplyr::select(col_no, value) %>% 
  dplyr::distinct()
# 
#          
openxlsx::setColWidths(results, "nested_species", cols = 1:ncol(to_save), widths = width_vec$value)


openxlsx::saveWorkbook(results,
                       file = here::here(params$sub_directory, "/",
                                         params$project,
                                         "results/", params$assay, 
                                         "/spreadsheet/",file_name), overwrite = T )


```

\newpage



